### ISSUE TITLE
`Network request failed` on mobile app

### ISSUE THREAD

**Issue by arcanistzed** [chen-rn/CUA#12]
I'm launching the app in Android Studio and the app opens and seems to work at first for a second, but then it switches to just showing `Network request failed` in the corner of the screen. The terminal says ` WARN  [TRPCClientError: Network request failed]`. No issues with the web version.
Any idea what the issue could be?

**Comment by alitnk** [comment]
I'm not sure but it might be related to how the tRPC base URL for client is created.
- [for web](https://github.com/chen-rn/CUA/blob/67c6203654e5b672afc6eda74c7c78421462df3f/packages/app/utils/trpc.web.tsx#L12)
- [for native](https://github.com/chen-rn/CUA/blob/67c6203654e5b672afc6eda74c7c78421462df3f/packages/app/utils/trpc.tsx#L25)

Maybe try hard-coding it and see if that for native and see if that works.

**Comment by chen-rn** [comment]
Yea it could be an url issue, is your Next app hosted on 3000?

**Comment by sfirrin** [comment]
I also ran into this. I didn't realize it at first but @chen-rn I think you're saying that having `yarn web` already running in another terminal and serving the API on localhost:3000 is a prerequisite to running `yarn native`? 

After I get `yarn web` running separately, `yarn native` works as expected. I was thinking that somehow `yarn native` would also serve the APIs locally but it makes sense that it would be handled by the Next devserver. If it would help I could open a PR to try to make that more clear in the setup doc

**Comment by chen-rn** [comment]
Oh yes! My apologies, indeed API is a part of Next Js backend(which means
that when you deploy production versions of your mobile app you'll want to
enter your vercel domain.

Yes please open a PR and clarify in the docs! That would be greatly
appreciated.

**Comment by chen-rn** [comment]
I'll close this for now and have added a comment beside `yarn native`, but I do agree the doc will likely need an overhaul sometime soon and welcome any PRs!!
