### ISSUE TITLE
[feature-request] Tauri example

### ISSUE THREAD

**Issue by timothymiller** [chen-rn/CUA#24]
I'm no fan of fedora wearing weirdos, but now that Tamagui Studio is a thing (that uses Tauri under the hood), it would be nice to see the desktop as yet another supported platform by create-universal-app.

**Comment by chen-rn** [comment]
Oh whoa! I didn't know Studio was released, I'll have to try it out this weekend :)

Re: Desktop
The RN for Desktop library maintained by MS doesn't seem super well maintained on the mac side. But we can definitely do something like Tauri, given that it's just the react app in a webview.

I've actually never played around with Tauri, but I can look at how Tamagui studio is set up and set one up for CUA. If it's easy, we _might as well_ have one!

A lot of exciting stuff happening, I'm also very open to PRs if you're up for a task!

**Comment by albbus-stack** [comment]
I've implemented the basic stuff for Tauri in the nextjs folder. Now it's available in the tauri branch of the repo, please test this yourself if you can as I cannot right now, as explained in [this PR](https://github.com/chen-rn/CUA/pull/30).

**Comment by albbus-stack** [comment]
@timothymiller have you tried it out? I forgot to tell you how to test it 😅. Just run `yarn desktop` in the root of the project.

**Comment by albbus-stack** [comment]
@timothymiller I've fixed a couple of things and now it's up on the main branch! You can now build the Tauri app with `yarn build-desktop`. #35 #37

**Comment by octalpixel** [comment]
Dumb question, but what is Tamagui Studio ? Couldnt find it
