### ISSUE TITLE
[BUG] Email Signup gives a 401 error on the user.create tRPC call

### ISSUE THREAD

**Issue by adamjq** [chen-rn/CUA#39]
First off, I really appreciate the project. This was very close to the tech stack I settled on after some digging around.

**Describe the bug**
Signing up a user with Email Signup gives a `401` error on the `user.create` tRPC call. The user signup completes in Clerk but the user isn't saved in the database.

User signup via an OAuth provider works and the user is saved in both Clerk and the DB, [which appears to be due to this line](https://github.com/chen-rn/CUA/blob/main/packages/app/features/signup/sso-oauth/screen.tsx#L34).

This bug relates to https://github.com/chen-rn/CUA/issues/5

Note - I've only tested this for Web signup with NextJS. It hasn't been tested with Expo.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start local database e.g. `npx supabase start` or equivalent
2. Run `yarn studio` and open Prisma studio
3. Run `yarn web`
4. Click on `Sign Up`
5. Sign up new user with Email/Password option
6. Enter verification code
7. Check Clerk dashboard and see user exists
8. Check database via Prisma studio and see no user

**Expected behavior**
tRPC call returns with 200 code. The user is created in the database and Clerk.

**Screenshots**

<img width="831" alt="user-create-error" src="https://user-images.githubusercontent.com/20121496/220089287-9f53b466-d42e-4506-a985-5aa2cdbfd5a0.png">

**Desktop**
 - OS: MacOS (Apple Silicon)
 - Browser: chrome

**Additional Info**

I've set up Prisma with Supabase and am testing against a local version of Supabase with Docker.

**Comment by chen-rn** [comment]
Hmm, Clerk has had some changes recently with their APIs, I wonder if this has to do with them. I'll have to look into this later!

Let me know if you figure it out!

**Comment by chen-rn** [comment]
in /email-verification/screen.tsx

Try changing from
<img width="680" alt="Screenshot 2023-02-20 at 1 10 44 PM" src="https://user-images.githubusercontent.com/36214945/220198966-a8cf1993-bdd6-41e3-a218-38c01570de98.png">

to 
<img width="576" alt="Screenshot 2023-02-20 at 1 11 15 PM" src="https://user-images.githubusercontent.com/36214945/220199045-980f66ee-5afb-4566-b55c-75b14521fd8f.png">

Just making sure we set the session first, THEN make an API call to our protected route, and finally pushing you to homescreen.

**Comment by adamjq** [comment]
Awesome thanks @chen-rn. I've tried your code suggestion in my project and confirmed it's working.

I've opened a PR to fix the issue here: https://github.com/chen-rn/CUA/pull/40

**Comment by chen-rn** [comment]
Glad it worked :) merged the PR!
