### ISSUE TITLE
Store user profile on the database at sign up time

### ISSUE THREAD

**Issue by RicardoPBarbosa** [chen-rn/CUA#5]
Is it possible to call trpc on app/utils folder to create a db entry for a user signing up?
If not, how should I approach that?

P.S:
@chen-rn  Thank you for your work on this. It's really awesome!

**Comment by chen-rn** [comment]
For sure!
I'll try to add this in, it _is_ a missing piece for sure
For now, if you'd like, you can call the create mutation in the user router with the email/name and whatever other information you want to store!

**Comment by chen-rn** [comment]
I've added this in the newest commit! Should work now :)

**Comment by yassinebridi** [comment]
Great stuff, the only thing that doesn't work is the user creation on social auth on web.
It's like it doesn't communicate well here: handleOAuthSignUpWithPress(app/features/signup/screen.tsx:18)

**Comment by chen-rn** [comment]
Ahh good catch, yea it seems my approach is a little off since the user will be redirected to the OAuth site.

Seems like a better way to do oauth is something like [this](https://clerk.dev/docs/component-reference/authenticate-with-redirect-callback). Lemme fix that.

**Comment by chen-rn** [comment]
Apologies for the delay, I made an update and tested on both expo and web so it should be working now!
The code might seem a little chunky but sharing auth/navigation code across mobile/web made this a little bit more complex.

I'll close this for now, if something else pops up I'll reopen it!

**Comment by yassinebridi** [comment]
Thank you Chen, really appreciate it 🙏
