### ISSUE TITLE
question: what is entries? 

### ISSUE THREAD

**Issue by colinricardo** [chen-rn/CUA#50]
first off, awesome work, very cool 

what is entry? in the schema -- it doesn't seem to be used anywhere

for me, it's always empty, and never gets written to the db

**Comment by chen-rn** [comment]
No worries :)
Great question haha, we should probably remove that.
Better/more relevant sample code is coming soon!

TLDR: Before CUA became CUA, I was working on a project that had entries as the DB schema. I ended up turning that code into the CUA template!

**Comment by colinricardo** [comment]
ah cool no worries! thanks for the quick response 

yeah the current `main` code makes it seem like login/logout isn't working as intended, but it's all good once adapted 

another question: is the intention to merge this branch? 
https://github.com/chen-rn/CUA/tree/expo-router

let me know if there's any specific areas you guys might want help with -- might be able to help with some small stuff :)

**Comment by chen-rn** [comment]
So that branch has already been merged into the main!(The main branch is using expo-router)
Maybe we should close that one now!

**Comment by colinricardo** [comment]
ah cool, I overlooked that 

noted, will have a look!
