### ISSUE TITLE
[BUG] After login on demo page getting prisma error

### ISSUE THREAD

**Issue by bidah** [chen-rn/CUA#67]
**Describe the bug**

sign up in https://cua-demo.vercel.app/
after sign up error shows up
```
Invalid `prisma.entry.findMany()` invocation: error: Error validating datasource `db`: the URL must start with the protocol `file:`. --> schema.prisma:9 | 8 | provider = "sqlite" // Change this to "postgresql" when you want to use PostgreSQL 9 | url = env("DATABASE_URL") | Validation Error Count: 1
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Monterrey
 - Browser: Edge

**Comment by albbus-stack** [comment]
@bidah We are aware of the problem (#19). If you are wondering, this bug is due to using sqlite in the template but postgres on the server.  @chen-rn has yet to resolve this by creating a different branch with postgres for the demo vercel deployment.
