### ISSUE TITLE
[FEATURE] Support drizzle-orm?

### ISSUE THREAD

**Issue by tonyabracadabra** [chen-rn/CUA#76]
https://github.com/drizzle-team/drizzle-orm

**Comment by chen-rn** [comment]
Happy to review a PR if anyone want to integrate Drizzle!
Seems like the right move

**Comment by albbus-stack** [comment]
I started the implemetation over on the [drizzle branch](https://github.com/chen-rn/CUA/tree/drizzle). @timothymiller @tonyabracadabra @chen-rn Please take a look at it and feel free to contribute since I'm not so sure of what we have to add other than my changes.

**Comment by albbus-stack** [comment]
@timothymiller @tonyabracadabra @chen-rn Now is also available the [drizzle sql branch](https://github.com/chen-rn/CUA/tree/drizzle-sql) that allows for simple local dev environment creation as it is in the prisma+sqlite version.

**Comment by chen-rn** [comment]
Looks great! Appreciate the good work :)

**Comment by albbus-stack** [comment]
With the [latest commit](https://github.com/albbus-stack/create-t3-universal-app/commit/2cd92268590548cd85be386ed084f5e0cc715d14) the command line tool also supports the `--with-drizzle-pg` and `--with-drizzle-sql` flags to clone the corresponding branches.

**Comment by albbus-stack** [comment]
If you encounter some problems in my implementation please open a new bug issue as the drizzle feature request is completed.
