### ISSUE TITLE
[BUG] Tamagui styling issues on Vercel

### ISSUE THREAD

**Issue by albbus-stack** [chen-rn/CUA#78]
**Describe the bug**
On Vercel deploys the Tamagui styling is not correct, while in a local environment everything works fine.

**To Reproduce**
Look at the demo app for example [cua-demo.vercel.app](https://cua-demo.vercel.app/) or just deploy your CUA instance to Vercel.

**Comment by Tomek20225** [comment]
I also encountered this issue. Unfortunately, I haven't found a solution. It may have happened in my project after the Tamagui upgrade, so rolling back may be helpful

**Comment by Tomek20225** [comment]
I haven't and I'm not really sure when I'll be able to, sorry. Maybe it's worth opening an Issue on Tamagui repo? Since this happened after Tamagui upgrade and CUA's solution isn't really non-standard

**Comment by Tomek20225** [comment]
#85 I implemented fixes in this PR

**Comment by albbus-stack** [comment]
Great work 🤟
